version: '3.5'

services:
  postgres:
    restart: always
    image: postgres:12.5
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=dc_datacube1234
      - DC_DB_USER=dc_user
      - DC_DB_PASS=localuser1234
      - DC_DB_NAME=datacube
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
    networks:
      - jnet
  
  dc-index:
    image: stevenmhill/dcindex:latest
    container_name: dcindex
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=dc_user
      - DB_PASSWORD=localuser1234
      - DB_DATABASE=datacube
      - DB_PORT=5432
    volumes:
        - /datacube:/datacube
    depends_on:
      - postgres
    networks:
        - jnet
    command: tail -f /dev/null  

  jupyterhub:
    image: stevenmhill/namibiahub:latest
    container_name: dchub
    ports:
      - "8082:8000"
    volumes:
           - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - jnet
      
  notebook:
    image: stevenmhill/notebook:latest
    container_name: dcnotebook
    links:
        - postgres:postgres
    depends_on:
        - postgres
    networks:
       - jnet
    volumes:
       - "./data:/home/jovyan/data"   
    entrypoint: sh -c 'jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/opt/app/data --allow-root'


networks:
    jnet:
      driver: bridge
      name: jnet  
