#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $DC_DB_USER WITH PASSWORD '$DC_DB_PASS';
  ALTER USER $DC_DB_USER WITH SUPERUSER;
  CREATE DATABASE $DC_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $DC_DB_NAME TO $DC_DB_USER;
  \connect $DC_DB_NAME $DC_DB_USER
EOSQL
